### ISSUE TITLE
invert colors results in extremely bright, white unreadable screen

### ISSUE THREAD

**Issue by erjoalgo** [OpenICC/xcalib#20]
See video attached, the inversion appears to do something but the result is an extremely bright, mostly white display.

https://github.com/OpenICC/xcalib/assets/5349288/4abf95a3-16ba-4481-a1c6-e876b1d10fdc

```
█[phantom][~][0]$ xcalib -i -a -v
Red Brightness: 0.000000   Contrast: 100.000000  Max: 1.000000  Min: 0.000000
Green Brightness: 0.000000   Contrast: 100.000000  Max: 1.000000  Min: 0.000000
Blue Brightness: 0.000000   Contrast: 100.000000  Max: 1.000000  Min: 0.000000
X-LUT size:             1024
█[phantom][~][0]$ xcalib -i -a -v
Red Brightness: 100.000000   Contrast: -inf  Max: 0.000000  Min: 1.000000
Green Brightness: 100.000000   Contrast: -inf  Max: 0.000000  Min: 1.000000
Blue Brightness: 100.000000   Contrast: -inf  Max: 0.000000  Min: 1.000000
X-LUT size:             1024
█[phantom][~][0]$ 
```

graphics card:

```
█[phantom][~][130]$ inxi -G
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    driver: amdgpu v: kernel
  Display: server: X.Org v: 1.21.1.7 driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,vesa dri: radeonsi gpu: amdgpu
    resolution: 3840x2160~30Hz
  API: OpenGL v: 4.6 Mesa 22.3.6 renderer: AMD Radeon RX 580 Series
    (polaris10 LLVM 15.0.6 DRM 3.49 6.1.0-16-amd64)
```
This is on debian bookworm and xcalib 0.8

```
█[phantom][~][0]$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
█[phantom][~][0]$ xcalib -version
xcalib 0.8
█[phantom][~][0]$ 
```

Color inversion works normally from a different machine using the same monitor, same OS, same xcalib version but different graphics card:

```
+ inxi -G
Graphics:
  Device-1: Intel WhiskeyLake-U GT2 [UHD Graphics 620] driver: i915 v: kernel
  Device-2: Chicony Integrated Camera type: USB driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.7 driver: X: loaded: modesetting
    unloaded: fbdev,vesa dri: iris gpu: i915 resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 Mesa 22.3.6 renderer: Mesa Intel UHD Graphics 620 (WHL
    GT2)
+ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
+ xcalib -version
xcalib 0.8
█[debian-x1-7th][~][0]$
```
